KCDO/ncg-cancer-modules-abdm

- src/main/java/com/karkinos/clinical/artifacts/util/Constants.java
- src/main/java/com/karkinos/clinical/artifacts/util/OPConsultationHelper.java
- src/main/java/com/karkinos/clinical/artifacts/vo/AllergyIntoleranceRequest.java
- src/main/java/com/karkinos/clinical/artifacts/vo/ClinicalData.java
Added AllergyIntolerance in Karkinos branch
> Added AllergyIntolerance in Karkinos branch

- src/main/java/com/karkinos/clinical/artifacts/util/Constants.java
- src/main/java/com/karkinos/clinical/artifacts/util/OPConsultationHelper.java
- src/main/java/com/karkinos/clinical/artifacts/vo/ClinicalData.java
- src/main/java/com/karkinos/clinical/artifacts/vo/CoMorbidity.java
- src/main/java/com/karkinos/clinical/artifacts/vo/ObservationWomenHealth.java
- src/main/resources/references/Input JSON.json
- src/main/resources/references/Output JSON.json
Added Co-Morbidities, ObservationWomenHealth feature, also created a folder to keep the input and output JSON
> Added Co-Morbidities, ObservationWomenHealth feature

- src/main/java/org/ncg/clinical/artifacts/service/ClinicalDataServiceImpl.java
- src/main/java/org/ncg/clinical/artifacts/util/Constants.java
- src/main/java/org/ncg/clinical/artifacts/util/FHIRUtils.java
- src/main/java/org/ncg/clinical/artifacts/util/OPConsultationHelper.java
- src/main/java/org/ncg/clinical/artifacts/vo/AdverseEvent.java
- src/main/java/org/ncg/clinical/artifacts/vo/ClinicalData.java
Added Adverse Events and updated Co-Morbidities section implementation
> Added Adverse Events and updated Co-Morbidities section implementation

- src/main/java/org/ncg/clinical/artifacts/service/ClinicalDataServiceImpl.java
- src/main/java/org/ncg/clinical/artifacts/util/FHIRUtils.java
- src/main/java/org/ncg/clinical/artifacts/util/OPConsultationHelper.java
- src/main/java/org/ncg/clinical/artifacts/vo/CancerDetails.java
- src/main/java/org/ncg/clinical/artifacts/vo/ClinicalData.java
- src/main/java/org/ncg/clinical/artifacts/vo/clinicalinformation/ClinicalInformation.java
- src/main/java/org/ncg/clinical/artifacts/vo/clinicalinformation/Comorbidity.java
- src/main/java/org/ncg/clinical/artifacts/vo/diagnostic/AttachmentDetail.java
- src/main/java/org/ncg/clinical/artifacts/vo/diagnostic/PanelDetail.java
- src/main/java/org/ncg/clinical/artifacts/vo/diagnostic/TestDetail.java
changed input structure json(attributes name) according to xsls
> changed input structure json(attributes name) according to xsls

- doc/Input JSON.json
- doc/Output JSON.json
- src/main/java/org/ncg/clinical/artifacts/util/Constants.java
- src/main/java/org/ncg/clinical/artifacts/util/FHIRUtils.java
- src/main/java/org/ncg/clinical/artifacts/util/OPConsultationHelper.java
- src/main/java/org/ncg/clinical/artifacts/vo/clinicalinformation/ClinicalInformation.java
- src/main/java/org/ncg/clinical/artifacts/vo/clinicalinformation/InvestigationAdvice.java
Changed patient height and weight to observations, allergyIntolerance to drugAllergy and several code fixes
> Changed patient height and weight to observations, allergyIntolerance to drugAllergy and several code fixes

- project/test/resources/OPConsultantRecord-Input.json
- project/test/resources/OPConsultantRecord-Output.json
- src/main/java/org/ncg/clinical/artifacts/util/FHIRUtils.java
Created package for storing input output json for OPConsultantRecord.
> Created package for storing input output json for OPConsultantRecord.

- doc/Input JSON.json
- doc/Output JSON.json
- generated/swagger-clinical-data-svc.json
- src/main/java/org/ncg/clinical/artifacts/util/Constants.java
- src/main/java/org/ncg/clinical/artifacts/util/FHIRUtils.java
- src/main/java/org/ncg/clinical/artifacts/util/OPConsultationHelper.java
- src/main/resources/docs-json/allTestsAndPanels.json
> Added encounter in patient

- src/main/java/org/ncg/clinical/artifacts/util/Constants.java
- src/main/java/org/ncg/clinical/artifacts/util/FHIRUtils.java
- src/main/java/org/ncg/clinical/artifacts/util/OPConsultationHelper.java
- src/main/resources/docs-json/allTestsNameCodeAndPanels.json
1. update medical History display with : History and physical report
2. Past Surgical history keep as Procedure with a date, status in MedicalHistory
3. add meta in MedicationStatement
> KCDO Review Comment Fixes

- project/test/resources/OPConsultantRecord-Input.json
- project/test/resources/OPConsultantRecord-Output.json
- src/main/resources/docs-json/cancerTypeDetails.json
Updated input/output and cancerTypeDetails json files.
> Updated input/output and cancerTypeDetails json files.

- project/test/resources/OPConsultantRecord-Input.json
- project/test/resources/OpConsultation-generic.json
- src/main/resources/docs-json/cancerTypeDetails.json
Fixed SNOMED codes for PCR and Cytogenetics
> Fixed SNOMED codes for PCR and Cytogenetics

- project/test/resources/OPConsultantRecord-Input.json
- project/test/resources/OpConsultation-generic.json
- src/main/java/org/ncg/clinical/artifacts/util/DiagnosticReportHelper.java
- src/main/java/org/ncg/clinical/artifacts/util/FHIRUtils.java
- src/main/java/org/ncg/clinical/artifacts/util/OPConsultRecordHelper.java
- src/main/java/org/ncg/clinical/artifacts/vo/clinicalinformation/ClinicalInformation.java
- src/main/java/org/ncg/clinical/artifacts/vo/clinicalinformation/PACNotes.java
- src/main/java/org/ncg/clinical/artifacts/vo/clinicalinformation/RadiationPlan.java
- src/main/resources/docs-json/allTestNameWithCodingAndPanels.json
- src/main/resources/swagger-clinical-data.yaml
PACNotes and RadiationPlan implementation, updated Swagger yaml file
> PACNotes and RadiationPlan implementation

- OPConsultation.fsh
Updated OpConsultation FSH file to add OT notes, SurgicalSummaryWithPostOpCourse, Follow up notes and Chemotherapy modules
> Updated OpConsultation FSH file to add 4 clinical information modules

- DiagnosticReport-output.json
- DiagnosticReport.fsh
DiagnosticReport FSH and output file
> DiagnosticReport FSH and output file

- OPConsultation-output.json
- OPConsultation.fsh
OpConsultation output and FSH file review comment fixes
> OpConsultation output and FSH file review comment fixes

- DiagnosticReport-output.json
- DiagnosticReport.fsh
Review comment fixes in DiagnosticReport FSH and Output file
> Review comment fixes in DiagnosticReport FSH and Output file

- OPConsultation-output.json
- OPConsultation.fsh
OpConsultNote Output and FSH file for AdultHematolymphoid
> OpConsultNote Output and FSH file for AdultHematolymphoid

- OPConsultation-output.json
- OPConsultation.fsh
Removed all FHIR validation errors except wrong code
> Removed all FHIR validation errors except wrong code

- DischargeSummary (AdultHematolymphoid).fsh
- DischargeSummary-output (AdultHematolymphoid).json
- OPConsultation-output.json
- OPConsultation.fsh
DischargeSummary for adultHematolymphoid
> DischargeSummary for adultHematolymphoid

- DiagnosticReport (AdultHematolymphoid).fsh
- DiagnosticReport-output (AdultHematolymphoid).json
- DischargeSummary (AdultHematolymphoid).fsh
Updated DiagnosticReport and DischargeSummary FSH and output file
> Updated DiagnosticReport and DischargeSummary FSH and output file

- 2ndEncounter/DiagnosticReportBreastCancer-2nd-Encounter.json
- 2ndEncounter/DiagnosticreportBreastCancer-2nd-Encounter.fsh
- 3rdEncounter/DiagnosticReportBreastCancer-3rd-Encounter.json
- 3rdEncounter/DiagnosticreportBreastCancer-3rd-Encounter.fsh
BreastCancer FSH and output file for Encounter 2
> BreastCancer FSH and output file for Encounter 2

- 4thEncounter/DiagnosticReportBreastCancer-4th-Encounter.fsh
- 4thEncounter/DiagnosticReportBreastCancer-4th-Encounter.json
BreastCancer FSH and output file for Encounter 4
> BreastCancer FSH and output file for Encounter 4

- BreastCancerUseCase/2ndEncounter/DiagnosticReportBreastCancer-2nd-Encounter.fsh
- BreastCancerUseCase/2ndEncounter/DiagnosticReportBreastCancer-2nd-Encounter.json
- BreastCancerUseCase/3rdEncounter/DiagnosticReportBreastCancer-3rd-Encounter.fsh
- BreastCancerUseCase/3rdEncounter/DiagnosticReportBreastCancer-3rd-Encounter.json
- BreastCancerUseCase/4thEncounter/DiagnosticReportBreastCancer-4th-Encounter.fsh
- BreastCancerUseCase/4thEncounter/DiagnosticReportBreastCancer-4th-Encounter.json
Added identifier in Organization in encounters 2, 3 and 4
> Added identifier in Organization in encounters 2, 3 and 4

- BreastCancerUseCase/1stEncounter/OPConsultationBreastCancer-InitialVisitEncounter-Output.json
- BreastCancerUseCase/1stEncounter/OPConsultationBreastCancer-InitialVisitEncounter.fsh
- BreastCancerUseCase/5thEncounter/OPConsultationBreastCancer-Post–DiagnosisMentalHealthSupportEncounter-Output.json
- BreastCancerUseCase/5thEncounter/OPConsultationBreastCancer-Post–DiagnosisMentalHealthSupportEncounter5.fsh
- BreastCancerUseCase/8thEncounter/DischargeSummaryBreastCancer-Surgery-Encounter8.fsh
- BreastCancerUseCase/8thEncounter/DischargeSummaryBreastCancer-Surgery-Encounter8.json
Changed encounter status, start and end date.
> Changed encounter status, start and end date.

- BreastCancerUseCase/10thEncounter/DiagnosticReportBreastCancer-10th-Encounter.fsh
- BreastCancerUseCase/10thEncounter/DiagnosticReportBreastCancer-10th-Encounter.json
- BreastCancerUseCase/9thEncounter/DiagnosticReportBreastCancer-9th-Encounter.fsh
- BreastCancerUseCase/9thEncounter/DiagnosticReportBreastCancer-9th-Encounter.json
DiagnosticReports for encounters 9 and 10 in BreastCancer sample data
> DiagnosticReports for encounters 9 and 10 in BreastCancer sample data

- BreastCancerUseCase/12thEncounter/DischargeSummaryBreastCancer-ChemotherapySession1-Encounter12-Output.json
- BreastCancerUseCase/12thEncounter/DischargeSummaryBreastCancer-ChemotherapySession1-Encounter12.fsh
- BreastCancerUseCase/1stEncounter/OPConsultationBreastCancer-InitialVisitEncounter-Output.json
- BreastCancerUseCase/1stEncounter/OPConsultationBreastCancer-InitialVisitEncounter.fsh
- BreastCancerUseCase/5thEncounter/OPConsultationBreastCancer-Post–DiagnosisMentalHealthSupportEncounter-Output.json
- BreastCancerUseCase/5thEncounter/OPConsultationBreastCancer-Post–DiagnosisMentalHealthSupportEncounter5.fsh
- BreastCancerUseCase/8thEncounter/DischargeSummaryBreastCancer-Surgery-Encounter8.fsh
- BreastCancerUseCase/8thEncounter/DischargeSummaryBreastCancer-Surgery-Encounter8.json
Code review changes for encounter1,5,8 and 12.
> Code review changes for encounter1,5,8 and 12.

- BreastCancerUseCase/2ndEncounter/DiagnosticReportBreastCancer-2nd-Encounter-MammogramReport.fsh
- BreastCancerUseCase/2ndEncounter/DiagnosticReportBreastCancer-2nd-Encounter-MammogramReport.json
- BreastCancerUseCase/2ndEncounter/DiagnosticReportBreastCancer-2nd-Encounter-UltrasoundReport.fsh
- BreastCancerUseCase/2ndEncounter/DiagnosticReportBreastCancer-2nd-Encounter-UltrasoundReport.json
- BreastCancerUseCase/3rdEncounter/DischargeSummaryBreastCancer-3rd-Encounter.fsh
- BreastCancerUseCase/3rdEncounter/DischargeSummaryBreastCancer-3rd-Encounter.json
- BreastCancerUseCase/4thEncounter/DiagnosticReportBreastCancer-4th-Encounter.fsh
- BreastCancerUseCase/4thEncounter/DiagnosticReportBreastCancer-4th-Encounter.json
Kiran's comment fixes in encounter 2, 3 and 4
> Kiran's comment fixes in encounter 2, 3 and 4
